name: Generate PDF Release

on:
  release:
    types:
      - published

jobs:
  generate_pdf_release:
    runs-on: ubuntu-latest

    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc and Dependencies
        run: sudo apt-get install -y pandoc texlive-latex-extra texlive-fonts-recommended librsvg2-bin


      - name: Convert README.md to PDF
        run: |
          pandoc -s -o README.pdf README.md

      - name: Upload PDF as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: README.pdf
          asset_name: README.pdf
          asset_content_type: application/pdf
