name: Generate PDF Release

on:
  push:
    branches:
      - main

jobs:
  generate_pdf_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc and Dependencies
        run: sudo apt-get install -y pandoc texlive-latex-extra texlive-fonts-recommended librsvg2-bin


      - name: Convert README.md to PDF
        run: |
          pandoc -s -o README.pdf README.md

      - name: Upload PDF as Workfow Artifact
        uses: actions/upload-artifact@v2
        with:
          name: README.pdf
          path: README.pdf
