name: Generate PDF Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate_pdf_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc and Dependencies
        run: sudo apt-get install -y pandoc wkhtmltopdf


      - name: Convert README.md to PDF
        run: |
          pandoc README.md -s --pdf-engine=wkhtmltopdf -f gfm -o README.pdf

      - name: Upload PDF as Workfow Artifact
        uses: actions/upload-artifact@v4
        with:
          name: README.pdf
          path: README.pdf
