name: Generate PDF Release

on:
  release:
    types:
      - published

jobs:
  generate_pdf_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc librsvg2-bin texlive-latex-base texlive-fonts-recommended

      - name: Convert README.md to PDF
        run: |
          pandoc -s -o README.pdf README.md

      - name: Upload PDF as Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: README.pdf
          path: README.pdf
