name: Generate PDF Release

on:
  release:
    types:
      - published

jobs:
  generate_pdf_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc and Dependencies
        run: sudo apt-get install -y pandoc texlive-latex-extra texlive-fonts-recommended librsvg2-bin


      - name: Convert README.md to PDF
        run: |
          pandoc -s -o README.pdf README.md

      - name: Upload PDF as Release Asset
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/octet-stream" --data-binary @README.pdf "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=README.pdf"
